// Auto-scraped from https://london.cityjsconf.org/speakers
const DETAILS = {
  "t1-open": {
    "desc": "Royal Geographical Society, 1 Kensington Gore, South Kensington, London SW7 2AR Our MC for the main stage",
    "bio": "Sara is a developer at Remote. Author of The Opinionated Guide to React. GraphQL and Open Source enthusiast. Conference Speaker and Airport expert. She's also a fan of horror movies, has talents such as banging sticks into a drum kit and saying the wrong thing at the wrong time."
  },
  "t1-0930": {
    "desc": "UX is changing with AI, where we go from clicking on boxes that are questionably accessible to just speaking things into existence. This talk will showcase how the role of JavaScript developers is changing in the AI age with practical steps and live demos.",
    "bio": "Tejas has been writing code since he was 8 years old. Today, Tejas loves code, loves people, and loves traveling around the world talking to people about code."
  },
  "t1-1000": {
    "desc": "Web development has always moved in cycles of hype, from frameworks to tooling. With the rise of large language models, we're entering a new era of 'vibe coding,' where developers shape software through collaboration with AI rather than syntax. This talk explores what that means for the future of coding, especially in frontend development, and how it echoes the past while redefining what comes next.",
    "bio": "Kitze loves to rant about webdev. He is the founder of Sizzy - the browser for developers. He created React Academy to teach webdevelopment. He's the creator of Zero To Shipped - the interactive video course for mastering Fullstack Development. He's documenting his journey on YouTube, streams on Twitch, and has a blog that he maintains once in a blue moon. He made Benji (https://benji.so), Twizzle (https://twizzle.app), ok-google.io (https://ok-google.io), JSUI (https://github.com/kitze/jsui), Glink (https://glink.so), showGPT (https://showgpt.co) etc."
  },
  "t1-1025": {
    "desc": "Not long ago, starting a Node.js project meant installing lots of packages just to handle environment variables, run tests, or use TypeScript. Now, those days are behind us, and 2026 is the time to make the switch. Node.js is stronger than ever, but there’s still a big issue: many people keep using outdated versions with known security problems. We need to talk about the current LTS schedule and why you should be on Node 24. This session will cover both the roadmap and hands-on examples. You’ll see how much you can do with just Node.js and your chosen framework, often with far fewer extra packages. We’ll look at built-in TypeScript support that works right away, so you can write and run TypeScript without a build step. We’ll also cover testing with node:test and node:assert, built-in .env configuration, and native fetch powered by Undici for HTTP. Other topics include watch mode for development, node:sqlite for embedded databases, and the stable Permission System for better security. This is not only about making things easier, but it’s also about security. Each dependency you skip is one less risk. When you publish packages, OIDC-based publishing to npm ensures your releases are securely linked to their sources and can be verified. Here’s something important: Node.js isn’t owned by any company. It runs on open governance and volunteers. By the end of this session, you’ll know the 2025-2026 roadmap, understand the new built-in features, and see why community involvement matters for security and the future. Your package.json will shrink, and Node.js is more worth your attention than ever.",
    "bio": "Matteo is the Co-Founder and CTO of Platformatic.dev with the goal to remove all friction from backend development. He is also a prolific Open Source author in the JavaScript ecosystem and modules he maintain are downloaded more than 12 billion times a year. Previously he was Chief Software Architect at NearForm, the best professional services company in the JavaScript ecosystem. In 2014, he defended his Ph.D. thesis titled \"Application Platforms for the Internet of Things\". Matteo is a member of the Node.js Technical Steering Committee focusing on streams, diagnostics and http. He is also the author of the fast logger Pino and of the Fastify web framework. Matteo is an renowed international speaker after more than 60 conferences, including OpenJS World, Node.js Interactive, NodeConf.eu, NodeSummit, JSConf.Asia, WebRebels, and JsDay just to name a few. He is also co-author of the book \"Node.js Cookbook, Third Edition\" edited by Packt. In the summer he loves sailing the Sirocco."
  },
  "t1-1120": {
    "desc": "What if your frontend didn’t need a deploy every time the product team wanted to rearrange a screen? Server-Driven UI lets the server send a declarative schema that the client renders at runtime — no redeploy needed. We’ll cover schema design, mapping responses to a component registry, handling actions declaratively, and the real tradeoffs around type safety and DX. You’ll leave knowing when this pattern is worth it and how to adopt it incrementally.",
    "bio": "Neciu Dan is the technical co-founder and tech lead of CareerOS, where he spearheads the development, maintenance, and scaling of the main application. Bringing over 12 years of engineering expertise to the table, Dan has a proven track record in the tech industry, having previously served as a Senior Product Engineer at the New York E-commerce brand, AdoreMe, and as a Senior Software Engineer at the food delivery company, Glovo. Beyond his technical contributions, Dan is an esteemed international speaker and mentor. He passionately encourages best development practices, with a keen focus on testing, accessibility, and security. His recent speaking engagements include esteemed conferences like React Alicante, Utah JS, Techorama Belgium, and Frontmania Netherlands."
  },
  "t1-1145": {
    "desc": "Use a module & a CLI to enable peer-to-peer deployments for any JS native application - such as an Electron or React Native app. Peer-to-peer over-the-air updates, production release flows with multisig for stakeholder sign-off, battle-tested in production with rapidly growing real-world apps with millions of new users per month. Open Source and free to use. No cloud, no fees, no outages.",
    "bio": "Writing JavaScript since '96, into Node.js from 0.8 (2012). Author, OSS Creator, Teacher, Consultant, Speaker helping to shape the ecosystem. Node Cookbook original and OpenJS Node.js Certifications lead. Driving innovation in the exciting peer-to-peer space, marking a new chapter in decentralized computing: pears.com."
  },
  "t1-1205": {
    "desc": "",
    "bio": ""
  },
  "t1-1225": {
    "desc": "The field of software engineering has changed dramatically in the last six months, whether you consented to it or not. But the new way of working has dangers that we're not taking seriously. In this talk, we'll explore how we can reframe our collective relationship with AI using the ideals of local-first development.",
    "bio": "⁠Open source troublemaker at Vercel. Creator of Rollup and Svelte"
  },
  "t1-1245": {
    "desc": "Video is everywhere on the web, from hero banners to product videos to full-blown streaming. However, while Lighthouse reports issues related to images, scripts, and more, it doesn't really address video performance. That means streaming can suffer for end users, resulting in buffering and slow starts, while businesses incur huge data transfer costs due to unoptimized delivery. In this talk, we'll explore some quick wins every developer should know: optimising video size and format, optimizing streaming for every device and network, and different video loading strategies to improve performance. You'll leave with a toolkit to make your videos load faster, play smoother, and feel as polished as the rest of your app, closing a significant gap that performance audits often overlook.",
    "bio": "Harshit designs, builds, scales, and optimizes high-performance media delivery solutions at ImageKit, bringing a solid foundation in API Design and System Architecture. Specializing in TypeScript, React, Node.js, and Next.js, he is always ready to get hands-on with whatever is needed to drive projects forward."
  },
  "t1-1400": {
    "desc": "We spend so long adopting well-worn patterns, and following accepted best practise, that we can forget about the fun that used to came from exploring the dark corners of our language. This talk covers some fundamentals of JavaScript and how they can be (ab)used to writer shorter and more compact code.",
    "bio": "Steven Goodwin (London, England) has been involved in computing, science, and technology from an early age, building his first synthesizer while still in his teens. As a systems architect he designed and built global systems for Unilever, Playfish, and Third Space Learning using a wide range of languages and technologies. He is also highly experienced on the small scale, with work on the iPhone, Arduino, and Raspberry Pi, as well as running teams of between 1 and 30 people. His position as an industry thought leader in technology implementations includes being a mentor at ed-invent, a start-up consultant, and a futurist. He has given talks around the world on topics as diverse as home automation, HTML5, game development, and quantum superpositions. To date he has written 8 JavaScript emulators and, should there be another lockdown in 2021, he will probably write some more!"
  },
  "t1-1420": {
    "desc": "Join us for an inspiring Women in Tech Panel spotlighting trailblazing leaders who are shaping the future of innovation. From engineering and product to entrepreneurship and AI, our speakers will share candid stories about their career journeys, lessons learned, and the challenges they’ve overcome in the tech industry. Whether you're just starting out or looking to level up your career, this conversation will offer practical insights, empowering advice, and meaningful connections to help you thrive in tech.",
    "bio": "Technical Lead and frontend engineering specialist with a strong track record of delivering scalable, high-quality digital solutions. Currently leading frontend development at VIOOH, Denise combines deep technical expertise with mentoring, agile collaboration, and a passion for building efficient, user-focused products. Director at HTMLASH LTD and Computer Science graduate from Manchester Metropolitan University."
  },
  "t1-1455": {
    "desc": "The industry has already learned how to break frontend monoliths apart without breaking the product experience. A similar shift is now happening in AI. This talk traces the move from federated UI and composable runtime systems to a federation of AI specialists—and shows why production AI works better when agents have clear roles, controlled tools, workflow hooks, shared collaboration context, and policy boundaries.",
    "bio": "Néstor is a Spanish platform engineer at Zephyr Cloud focused on Module Federation, microfrontends, edge-native deployments, and distributed systems. He contributes to open source around tools such as tRPC, the T3 Stack, and Module Federation, and regularly writes and speaks about frontend architecture, infrastructure, and modern software delivery through his blog, talks, and engineering posts."
  },
  "t1-1510": {
    "desc": "Throughout history, empires rise and fall. Throughtout web development, frameworks rise and fall. In 2026, we are firmly in \"late stage React\", where young devs can't remember the world any other way, and older devs are keeping their eye on the horizon for what's next. What if I told you there was a TypeScript-first UI framework created by a member of both the React _and_ Svelte core teams focused on fine-grained reactivity and rendering speed that will look instantly familiar to you? I'd like to introduce you to Ripple, show you around its syntax and philosophy and stimulate your mind out of the Present and into the Future.",
    "bio": "American expat living in Spain, author of Redux Form, Final Form, and currently building the best CRM in the world at Attio."
  },
  "t1-1530": {
    "desc": "Micro-Frontends are the distributed architecture for the user interfaces that are solving not only technical but also organizational challenges. In this session, you will learn the most common anti-patterns I've seen in the past 10 years of implementing and consulting worldwide companies in their journey into the micro-frontends architecture. Whether you are an expert or a newbie, in this talk, you will learn how to properly structure your micro-frontends architecture and how to avoid common mistakes while building micro-frontends.",
    "bio": "Luca Mezzalira has been associated with the industry since 2004 and has lent his expertise predominantly in the solution architecture field. He earned accolades for revolutionizing the scalability of frontend architectures with micro-frontends, from increasing the efficiency of workflows to delivering quality in products. Luca is known as an excellent communicator who believes in using an interactive approach for understanding and solving problems of varied scopes."
  },
  "t1-1600": {
    "desc": "In this panel we'll discuss the current state of generative AI, how systems built on top of it work, and what happens if the exceptionally resource intensive infrastructure underneath it fails. We'll cover the possible ramifications for our industry, the ethical dilemas and project out into the future around this controversial and category defining emerging programming technique.",
    "bio": "David is the Director of Architecture for NewDay, and the founder of Electric Head Software. Focusing on iterative software delivery, developer mentoring and cultural change - mostly working with London-based organisations. He speaks about software design, culture, and ethics in technology - rounded out by an assortment of talks about software that probably doesn't need to exist but makes the world a little more fun. David has previously served as the chief coding technical architect for JustGiving and helped market-leading organisations including JUST-EAT, Trainline and Vodafone improve their technical capabilities. David is a Microsoft MVP, has been part of the OpenUK Honours list for open-source advocacy, and is a twice bestselling author of children's books about programming."
  },
  "t1-1645": {
    "desc": "JavaScript's best part is higher-order functions. You will discover why this is the best way to program.",
    "bio": "Douglas Crockford is the author of How JavaScript Works. He has been called a JavaScript Guru, but he is more of a Mahatma. He was born in Frostbite Falls, Minnesota, but left when he was only six months old because it was just too damn cold. He has worked in broadcasting, learning systems, small business systems, office automation, games, interactive music, multimedia, location-based entertainment, social systems, and programming languages. He is the inventor of Tilton, the ugliest programming language that was not specifically designed to be an ugly programming language. He is best known for having discovered that there are good parts in JavaScript. That was the first important discovery of the Twenty First Century. He also discovered the JSON Data Interchange Format, the world’s most loved data format."
  },
  "t2-open": {
    "desc": "",
    "bio": ""
  },
  "t2-1000": {
    "desc": "Frontend tooling moves at breakneck speed, but the foundations of great web applications remain surprisingly constant. In this talk, Daniel explores how to architect projects that will thrive across technology shifts — from framework migrations to evolving hosting landscapes. Drawing from his work leading the Nuxt core team and collaborating with global developer communities, Daniel shares patterns, pitfalls, and practical strategies for building software that stays resilient, adaptable, and joyful to work on.",
    "bio": "Daniel leads the Nuxt core team - previously CTO of SaaS startup and founder of a creative agency focusing on clarity of vision and message. His open-source work has a focus in the Vue.js and Nuxt ecosystems and he's involved in consultancy with companies around the world, particularly around JAMstack, serverless and software architecture. He's based in Scotland where he lives with his family and cat."
  },
  "t2-1025": {
    "desc": "The component model made popular by React was the key to its success. By giving developers precise control over how interfaces are created, composed, and reused, React enabled an entire generation of high-quality user interfaces and thoughtful user experiences. Today, we’re at a similar inflection point… The rise of large language models has introduced a new way of interacting with machines. What began as text-based interfaces has steadily evolved into richer experiences, with UI components now being rendered and orchestrated by LLMs themselves. Yet most of these systems remain constrained by a familiar paradigm: invoking pre-made, static components. But let’s be honest, most LLMs are better at writing frontend code than me! This creates a great opportunity to rethink UI with React: moving beyond fixed component trees toward true generative UI In this talk, through concrete examples and live demos, we’ll explore how React fits into the emerging spectrum of generative UI, including: * Static React UI templates exposed through tools * Declarative, configuration-driven interfaces orchestrated by agents * Fully generative React interfaces authored on the fly by LLMs",
    "bio": "Ruben Casas is a Staff Vibe Engineer at Postman. Always exploring what's next: Currently playing with MCP and MCP Apps, AI-native developer tools, self-generating UIs, and the future of human + machine collaboration."
  },
  "t2-1120": {
    "desc": "Here's something most Node.js developers don't realize: PM2's cluster module silently imposes a ~30% performance tax through hidden IPC coordination overhead. Every request pays this cost for master-worker communication, and most teams accept it as the price of scaling Node.js applications. With Watt, we eliminated this overhead using SO_REUSEPORT, achieving 93% faster median latency by letting the Linux kernel handle load distribution directly—no master processes, no IPC, zero coordination cost. In this talk, we'll walk through our production benchmarks on AWS EKS and show how Watt delivers not just raw performance, but also multithreaded SSR, distributed caching, full observability with Prometheus, and seamless horizontal scaling—all while dramatically reducing your infrastructure costs.",
    "bio": "Node.js TSC Member, Principal Engineer at Platformatic, Polyglot Developer. RPG and LARP addicted and nerd on lot more. Surrounded by lovely chubby cats."
  },
  "t2-1145": {
    "desc": "Most of the talk around AI is about revolution, this is about taking an LLM off the big tech platform for simple daily improvements. I built a fully private digital butler that actually is personal. It exists on my computer, and stores only what I tell it to. It shares no data with the world, and helps me stay organised with useful, focused interactions.  I’ll show you how I made it, so you can build your own too. More importantly, I’ll help you think through a process of taking the scary acronyms of AI and LLMs into something **small, friendly, and genuinely helpful**. Something that stays **private and under your control**, and lets you own your data. Looking forward to sharing what I built, and hopefully inspiring you to do the same.",
    "bio": "Alvin is a developer advocate at Yoto working in IoT audio. Before that he did developer relations for Unleash and Contentful, focusing on feature flags and headless CMS. Previously, he was a lead engineer for Dow Jones at the Wall Street Journal and had various front-end roles over 8 years working on graphics, maps, games, and 3D. He’s happiest working on visual challenges with designers."
  },
  "t2-1205": {
    "desc": "Observability is the ability to measure the current state of a system. SREs are familiar with OpenTelemetry signals and how they can be used to diagnose issues. Yet in the frontend world, we’re behind the curve. Join me as I dive into the current state of OpenTelemetry for Web. I’ll cover a simple example of logging, metrics and tracing using OTel web, specifically the Client Instrumentation libraries, and the types of metrics and traces we should collect to diagnose performance issues and client usage in UIs.",
    "bio": "Carly is Developer Advocate Lead at Elastic, based in London, UK. Before joining Elastic in 2022, she spent over 10 years as a software engineer at a large investment bank, specialising in front-end web development and agility. She is a UI developer who occasionally dabbles in writing backend services, a speaker, and a regular blogger. She enjoys cooking, photography, drinking tea, and chasing after her young son in her spare time."
  },
  "t2-1225": {
    "desc": "In 2026, shipping a heavy library like Formik or React Hook Form is often an unnecessary performance tax. This \"delete code\" session showcases how to use the Constraint Validation API, the Popover API, and native HTML Form Validation to build complex, accessible, and high-performance forms with zero external dependencies. We will compare the bundle size and TBT (Total Blocking Time) of a \"library-less\" form versus a traditional one, proving that \"doing less\" is the ultimate developer experience.",
    "bio": "Trust Jamin Okpukoro is a developer advocate and senior technical writer with a strong background in software engineering. Over the past few years, he has consistently enhanced developer experiences across various developer products by creating impactful technical content and leading strategic initiatives. His work has helped increase product awareness, drive user engagement, boost sales, and position companies as thought leaders within their industries."
  },
  "t2-1245": {
    "desc": "In this talk, we’ll explore how to build multimodal AI agents that understand voice, interpret images, hold short-term memory, and respond intelligently - all running entirely in the browser. No server, no cloud APIs, and no installation. Using modern tools like WebGPU and WebAssembly, we’ll see how far the open web has come in enabling real-time, privacy-preserving AI experiences.",
    "bio": "In this talk, we’ll explore how to build multimodal AI agents that understand voice, interpret images, hold short-term memory, and respond intelligently - all running entirely in the browser. No server, no cloud APIs, and no installation. Using modern tools like WebGPU and WebAssembly, we’ll see how far the open web has come in enabling real-time, privacy-preserving AI experiences."
  },
  "t2-1400": {
    "desc": "This presentation will detail a methodology to help you select the right Generative AI (GenAI) model by defining project needs and constraints first, assessing the available data, and finally, selecting the appropriate model type and processing location. Once you have narrowed down the model type, we'll cover how to actually evaluate the mode fit for your project needs.",
    "bio": "Ali Spivak is a lead on the Chrome Developer Relations team at Google, where she manages a global team covering Web & Chrome AI, Chrome Extensions, Chrome Developer Tools, and Chrome on Android. With prior experience at Mozilla, Okta, Cisco, and several startups, Ali has a background in web development and leading developer relations teams."
  },
  "t2-1425": {
    "desc": "Modern React applications are no longer just UI layers. They sit at the boundary of a distributed system, coordinating APIs, third-party services, feature flags, client-side caches, async rendering, and user-critical flows that can fail in several ways, some loud and others not so much. This talk looks at resilience from the frontend outward. Not in a “self-healing systems” sense, but in the practical sense of baking better guarantees into the way we design React applications, so they fail more predictably, recover more safely, and surface the right signals when things go wrong. Using real production lessons from Smallpdf, including a 35-day region-specific payment failure that went undetected while most metrics looked healthy, we’ll examine why frontend resilience is often less about preventing total outages and more about containing partial, conditional, and business-critical failures before they become expensive. We’ll explore how React architecture directly shapes recovery speed, debugging precision, and operational confidence, especially at scale. Along the way, we’ll cover the frontend as a distributed system boundary, why platform uptime does not equal successful user outcome, how to use component trees, Suspense boundaries, and error boundaries as failure-containment tools, and how feature flags can either improve safety or quietly multiply risk depending on how they are structured.",
    "bio": "Faris is an experienced engineer, international conference speaker, and workshop instructor with a focus on React, Next.js, web architecture, and resilient system design. He has a strong interest in startups, having worked at early-stage companies in roles ranging from founding teams to scaling organizations from 1 to 100 people. His expertise includes engineering leadership, designing career ladders from scratch, and managing teams of over 10 engineers. As a front-end subject matter expert, Faris has built systems used by millions of users. His work spans greenfield projects and long-running products. He has worked in industries including Connected TV, Fintech, SaaS, and Fitness, with companies such as Smallpdf, Fiit, Discovery, GCN, Eurosport, and Navro (formerly Paytrix). Faris focuses on building user-centric, performant, and maintainable applications. He takes a particular interest in observability and monitoring, making systems easier to debug and improve. He shares his knowledge by organizing the Zurich.js meetup in Switzerland and speaking at international conferences on web development, engineering leadership, and scalable systems. In his spare time, Faris contributes to developer tools like Raycast and reflects on questions like why the build works on his machine but fails everywhere else."
  },
  "t2-1450": {
    "desc": "React has been shaping how we build user interfaces for over a decade. But its journey hasn’t exactly been smooth. From early skepticism around JSX and “mixing HTML with JavaScript” to debates about hooks, concurrency, and RSC, React has sparked more controversy—and innovation—than almost any library in the web ecosystem. In this talk, we’ll revisit the past that led to React’s creation, explore the many “trouble in paradise” moments that challenged the community, and look at what’s coming next—from the React Compiler to new architectural ideas shaping the framework’s future. Along the way, we’ll uncover the deeper ideas behind React—composition, predictable data flow, and powerful abstractions—and reflect on what a decade of React can teach us about the evolution of software itself.",
    "bio": "Matheus is a Staff Front-End Engineer at Medallia, building their surveys platform and helping them shape the customer experience market with React, and a Google Developer Expert in Web Performance. His areas of interest include React and its ecosystem, JS and compile-to-JS languages, DX, and perceived performance optimization. Aside from public speaking about these, he also volunteers at TechLabs, teaching front-end development."
  },
  "t2-1525": {
    "desc": "This talk will take you through how AI can improve your e-commerce website to increase conversion and customer joy. The talk will cover Agents and how MCP helps build reusable agents",
    "bio": "Chris is a Senior Engineer at Microsoft , with 20 years in the IT industry, focused on AI and JavaScript. He also lectures at University of Oxford on AI and Agents."
  },
  "t2-1545": {
    "desc": "Most serialization formats used in JavaScript were never designed for JavaScript. JSON can’t handle circular references or shared objects; Protobuf and Avro require schemas; MessagePack and CBOR still see data as a tree. In this talk, I will introduce JSBT – JavaScript Binary Transfer, a binary format designed specifically for JavaScript object graphs. It supports circular references, Maps, Sets, BigInts, TypedArrays, class instances and achieves huge size reductions (10,000 objects → 62 KB). A deep dive into how it works, why it exists, and how it can change the way JS services exchange data.",
    "bio": "Alexander Cheprasov is a Principal Software Engineer based in London, specializing in high-load systems, trading platforms and distributed JavaScript applications. He is the creator of JSBT — a binary serialization format designed specifically for JavaScript object graphs. Alexander has extensive experience in TypeScript, Node.js, Go, scalable architectures and performance engineering. He is passionate about developer tools, data processing and building robust, elegant systems."
  },
  "t2-1610": {
    "desc": "If you write JS or TS, it probably feels like every tool you use daily is being rewritten in Rust. This has advantages (have you heard that Rust is \"blazing fast\"?), but also potential downsides. The evolution of JS from the dark days before async/await was fuelled by tooling written in JS. If our tools migrate to a language we don't know, will we lose the ability to control or customize them? In this talk, I'll explain how Oxc is aiming to \"square the circle\" - providing rich customisation via plugins written in JS, but maintaining the exceptional performance of Rust - and take you into the nerdy details of memory layouts, allocators, garbage collection, and the tricks that make it possible to have our Rusty cake and eat it with a JS fork.",
    "bio": "Jim (overlookmotel) is an unashamed compiler nerd and performance nut. Member of core team of Oxc, the JS/TS parser/transpiler/minifier/linter that sits at the base of Vite’s stack. Came to software development by a circuitous route via film production, music festivals, and running a travelling cinema."
  },
  "t3-1125": {
    "desc": "What started as a secure, isolated iFrame to ensure user confidence soon turned into a performance hurdle in key markets like Brazil, where load times hit double digits. In this talk, we’ll show you how we transformed that iFrame-based approach into a blazing-fast, data-driven payment platform. This isn’t another framework story; it’s an engineering one. We had to make bold decisions to transform that single-page approach into a fast, reliable, and scalable payment ecosystem. We'll dive into the technical journey and the data that drove our decisions, revealing how we achieved dramatic speed improvements without sacrificing reliability. Come see how we turned a slow lane into a fast track, all grounded in real-world performance data. Under the hood, we used Vue.js to make it happen, but the real takeaway is how data guided the architecture. This session unpacks what we built, what didn’t work, and the hard-earned lessons about performance that go beyond any single framework.",
    "bio": "I am a passionate Software Engineer passionate about Frontend with over 15 years of experience in the ever-evolving landscape of web technologies, I've had the privilege of witnessing and contributing to the transformation of the digital world. Whether streamlining codebases, introducing micro-frontend (Mosaic 8), PWAs, or implementing cutting-edge technologies, my experience enables me to lead in crafting scalable and efficient architectures that meet and exceed the demands of modern web applications."
  },
  "t3-1205": {
    "desc": "",
    "bio": ""
  },
  "t3-1400": {
    "desc": "I work with AI daily - building tools, refactoring codebases, shipping features. It's genuinely made me more productive. But somewhere along the way I learned that the real skill isn't prompting, it's evaluation. A 2023 University of Iowa study found that AI and pigeons use the same associative learning process - pattern matching, not reasoning. I'm not saying that to be dismissive. It's incredibly powerful. But it means you're working with a very fast pigeon, and you need to know when the patterns have gone wrong. And they will. This talk covers: Real examples of my pigeon going off track and how I caught them (including the time it moved 160 files to completely the wrong place) The verification habits I've built into my workflow Why \"trust but verify\" isn't enough - you need to know what to verify Building guardrails so you can move fast without breaking things No hand-wavy thought leadership. Just what I've learned from doing the work.",
    "bio": "Meet Scott, a no-nonsense Svelte ambassador, team lead, and the go-to for real-world web dev advice. He organizes Svelte Society London, blogs what he learns, and creates videos that cut through the hype and get straight to what works. Scott’s all about community, making complex tech simple, and sharing both wins and learning moments. If it’s SvelteKit, TypeScript, or Tailwind, he’s probably using it (and telling you why pnpm is the only way!)."
  },
  "t3-1445": {
    "desc": "With supply chain attacks increasingly targeting the developer's machine, we need to start looking into hardening that. Let's see how you can eliminate most risks form malicious NPM packages in your local dev environment with one setup of under 5 minutes.",
    "bio": "Full-stack engineer and technology researcher. Leads Security Lab team at MetaMask working on LavaMoat and Endo. Started using Node.js at v0.8 and never stopped. Enjoys innovating and teaching security, diagnostics and maintainability. One of the oldest members of meet.js Poland community - both as a speaker and organizer. Hacking JavaScript since his teenage years."
  },
  "t3-1520": {
    "desc": "Modern JavaScript apps demand more from the browser than ever. As rendering, scripting, layout, and user input all fight for time on the main thread, even well-built apps can suffer from slow interactions, jank and dropped frames. In this talk, we'll explore how to build fast, smooth web experiences by strategically moving work off the main thread.",
    "bio": "I am a Senior Engineer – Web Standards Technologist at Samsung R&D Institute UK (Samsung Electronics) where I work closely with several W3C working groups – including Web Applications, Devices and Sensors, Accessible Platform Architecture, and Web DX – to help shape the capabilities of the modern web. My work sits at the intersection of standards development, and developer advocacy. Before stepping into the standards world, I was a front-end engineer building high-performant, user-centric web applications with React and Angular for major clients. Having lived on both sides of the table – as a developer who consumes the platform and now as someone who helps define it – I bring unique perspective on how the web evolves and why certain decisions are made. I write code, and now a whole bunch of standards too. Outside of work, you will find me travelling or jamming to some cool music."
  },
  "t4-open": {
    "desc": "",
    "bio": ""
  },
  "t4-1125": {
    "desc": "As AI starts writing, refactoring, and reviewing more of our code, security risks are evolving faster than ever. Imagine what happens when an LLM-generated snippet quietly introduces an injection flaw or when Copilot autocompletes a secret straight into your repo? This talk aims to show how we can keep AI-assisted development secure — not by slowing developers down, but by empowering them. With Semgrep, a lightweight and open-source static analysis tool built for developers, we will use semantic rules that catch vulnerabilities in JavaScript, TypeScript, and Node.js code before they hit production. This talk will be a mix of storytelling, live demos, and real-world lessons. We’ll use rules that detects an AI-generated security flaw, integrate Semgrep's CI/CD tool into GitHub Actions, and show how modern teams can automate their code review guardrails while keeping their developer flow intact. By the end of this talk, you’ll walk away with the confidence to bring AI security scanning straight into your CI/CD — no expensive tooling, no friction, just smart protection.",
    "bio": "Paul is a software engineer passionate about building reliable, user-focused applications. With over five years of experience in software development, Paul now exploring how AI and security tools can transform the way we write and protect code. While working as a Technical Support Engineer at Supabase, he is currently pursuing an MSc degree in Artificial Intelligence at the University of Salford, Manchester where he learns to apply AI to practical, real-world engineering challenges."
  },
  "t4-1205": {
    "desc": "Today’s interfaces often expose agents as simple chats or side panels, while real products are organized around clear domains and responsibilities. This session explores how to use A2UI to deliver complete agentic experiences as microfrontends, each aligned to a specific product context and owned by a dedicated team. Instead of sprinkling agent calls across many components, an agentic microfrontend becomes the primary interface for a given task space, with server-side agents describing UI updates via A2UI and the microfrontend rendering them using its own trusted design system.",
    "bio": "Alex is a Senior Solutions Architect at AWS with 20 years of IT experience in expert and leadership roles. He is a strong advocate of agile and DevOps practices, and he enjoys seeing serverless, cloud-native and event-driven architectures deployed at scale. He has delivered large transformation projects and successfully developed own and customers’ businesses. As an international speaker, he has held advanced technology sessions at a wide range of events."
  },
  "t4-1400": {
    "desc": "I built a production app now used by contractors in a fraction of the time it would have taken me a year ago. Not because I wrote less code, but because I learned to orchestrate. We're in the middle of a fundamental shift: from writing every line of code to orchestrating AI agents that help us build. Paradoxically, this requires both stronger technical judgment and more product thinking - knowing what to build and why, not just how to implement it. Through a case study of building this product, I'll share three approaches to AI-assisted development, orchestration patterns for coordinating multiple AI agents and tools, and strategies for navigating challenges like the \"Hyperspecificity Paradox.\" You'll leave with a strategic framework for using AI across the full build cycle - ideation, discovery, architecture, implementation, deployment - and actionable patterns you can apply immediately. Why This Matters for CityJS Attendees: When everyone has access to AI intelligence, what becomes the differentiator? I argue it's agency, curiosity, product thinking, and the builder's mindset. Orchestration elevates developers from implementation details to strategic decisions about what should be built. This talk equips JavaScript developers with both the philosophy and practical patterns to thrive in this new paradigm.",
    "bio": "Nkechi is a full-stack product engineer and multidisciplinary technologist documenting the transition from traditional development to AI orchestration through hands-on experimentation and real-world projects. She's currently building the future of KYC and Digital Identity as a senior product engineer at Vouchsafe while developing an AI workflow app in stealth mode. She's passionate about creating products that reshape how people interact with the world around them."
  },
  "t4-1445": {
    "desc": "",
    "bio": ""
  }
};
